### ISSUE TITLE
Sophia to begin literature report 

### ISSUE THREAD

**Issue by markziemann** [markziemann/Gene-function-imputation#1]
I'm assigning you the literature report on ML/DL/AI techniques on large transcriptome data. 

Deadline 7th August

If you have any doubts, feel free to write questions here or by email , phone etc.

**Comment by soph-r** [comment]
Did you want me to focus my literature search on methods mentioned in yesterday's meeting (i.e. hierarchical clustering, WGCNA, random forest or SVM, and collaborative filtering), or search more broadly to include other methods I find?

Was there also a certain number of articles that you wanted me to use in the report?

**Comment by markziemann** [comment]
>Did you want me to focus my literature search on methods mentioned in yesterday's meeting (i.e. hierarchical clustering, WGCNA, random forest or SVM, and collaborative filtering), or search more broadly to include other methods I find?

I think you should mention these, but not go into too much extra detail. The main purpose of your literature report will be the cutting edge ML/DL/AI techniques that you can find. Some of which we can apply in future studies.

> Was there also a certain number of articles that you wanted me to use in the report?

I think the literature report should be 500-1000 words and reference between 10 and 30 sources. They don't all need to be journal papers; you might find some interesting blog posts, pre-prints, conference posters, etc 
Good luck
