### ISSUE TITLE
Sophia to run example recommenderLab workflows

### ISSUE THREAD

**Issue by markziemann** [markziemann/Gene-function-imputation#11]
I have installed the recommenderLab R package on the Rstudio instances - can you run the example we discussed with the meals/persons?

https://cran.r-project.org/web/packages/recommenderlab/index.html

**Comment by soph-r** [comment]
Yes, I'll happily give it a try!

**Comment by megan-soria** [comment]
MovieRecommender.Rmd

Script is on the repository.
Well done @soph-r !
