### ISSUE TITLE
Data shape might be causing negatives in the subtraction matrix. Wil recheck

### ISSUE THREAD

**Issue by megan-soria** [markziemann/Gene-function-imputation#14]
https://github.com/markziemann/Gene-function-imputation/blob/e261019801edb764ae981635c6af9cb6c9ce547f/YeastClustersWithGO.Rmd#L437

**Comment by megan-soria** [comment]
Checked and traced variables and it seems fine.

cluster1_wGO: object from function wcorr_cluster
wcorr_cluster: a nested list of genes belonging to a cluster with their corresponding weighted correlations.

**Comment by markziemann** [comment]
Okay now you'll need to check the data upstream of this, including a lot of "sanity checking"
