### ISSUE TITLE
Changed the denominator of the normalization for wcorr2_cluster function

### ISSUE THREAD

**Issue by megan-soria** [markziemann/Gene-function-imputation#17]
https://github.com/markziemann/Gene-function-imputation/blob/53d9eab4d380ec7e86c2f630fd4cda0a994ccf9e/YeastClustersWithGO.Rmd#L388

**Comment by megan-soria** [comment]
In the first function, the GO terms were averaged by just getting the standard mean.
Upon inspection, I remembered that if we were to treat the Correlation Values as the "weight", we should be using the formula for the weighted average instead. The difference being that the denominator is the sum of all the weights.

In this ver2 of the function, corr_colsum is the sum of all the correlation values for the first blind gene in cluster 1 which is located in column 1:

corr_colsum <- sum(weighted_go[,1])


_Is this a valid change? Or is the normal Mean sufficient?_

**Comment by markziemann** [comment]
> Is this a valid change? Or is the normal Mean sufficient?

I think the Mean is sufficient. Indeed the correlation values will become our weights.

**Comment by megan-soria** [comment]
Sum of the correlation values will be used as the denominator to get the weighted ave.
