### ISSUE TITLE
Begin with filtering yeast bulk data

### ISSUE THREAD

**Issue by markziemann** [markziemann/Gene-function-imputation#2]
Create an Rmd file to begin working with yeast data

Here is the bulk data: http://dee2.io/mx/

Begin with scerevisiae_se.tsv.bz2

Here is the QC data scerevisiae_qc.tsv.bz2

Quantify the number of PASS, WARN and FAIL runs.

Select only the PASS samples for downstream analysis for now

Aggregate the SRR run data to SRX experiment (I have code to do this https://github.com/markziemann/getDEE2/issues/7#issuecomment-639290203)

**Comment by megan-soria** [comment]
[ ok] Create an Rmd file to begin working with yeast data

[ ok] Quantify the number of PASS, WARN and FAIL runs.

[ ok] Select only the PASS samples for downstream analysis for now
*Comment: I filtered the scerevisiae_se.tsv in this step. Is that needed or should I just generate a list?

[ in progress ] Aggregate the SRR run data to SRX experiment 
*Comment: I'm not sure if I get what the function does. Clarifications:

1. Should I used the getDEE2 function to download scerevisiae and generate x?
2. Where can I get the SRA run accession numbers? Is it the same as the data found in column 1 of scerevisiae_se.tsv?
3. I don't get the second parameter of the srx_agg function. Should I just put counts="GeneCounts"?
4. I tried using the example on the srx_agg and generated the x using ecoli. I used in on the function but got an error. Kindly check what i missed.

(commit 9710ec9918d25c58b1b4d6e57918d0f88bbda596)

**Comment by markziemann** [comment]
>[ in progress ] Aggregate the SRR run data to SRX experiment
*Comment: I'm not sure if I get what the function does. Clarifications:

>Should I used the getDEE2 function to download scerevisiae and generate x?
Where can I get the SRA run accession numbers? Is it the same as the data found in column 1 of scerevisiae_se.tsv?
I don't get the second parameter of the srx_agg function. Should I just put counts="GeneCounts"?
I tried using the example on the srx_agg and generated the x using ecoli. I used in on the function but got an error. Kindly check what i missed.

This comes down to the organisation of the data. When downloaded from DEE2 it is organised by SRR (sequencing run). For a minority of datasets, there are multple SRRs. It makes sense to aggregate these to SRX nmbers. The metadata linking accession numbers can be found here: http://dee2.io/metadata/

No you shouldn't use the getDEE2 function. You should download the bulk data from here: http://dee2.io/mx/ for example scerevisiae_se.tsv i correct.

This is the important part of the function which does the aggregation.
```
 SRX_dat <- vapply(X=unique(mds$SRX_accession) ,
        function(srx) {
            srrs<-rownames(mds)[which(mds$SRX_accession %in% srx)]
        rowSums(x[[IDX]][,srrs])
    } , numeric(n))
```
The E.coli examply might not work because there's only 1 run per SRX. That's my mistake. I've amended the function to handle this case. https://github.com/markziemann/getDEE2/issues/7#issuecomment-655805451

**Comment by megan-soria** [comment]
Pushed some new code. Please check if its correct.

commit a6b63cbb2733fec5ba077c0b6b2d13e85fdda5e8
