### ISSUE TITLE
Directly read bz2 data

### ISSUE THREAD

**Issue by markziemann** [markziemann/Gene-function-imputation#3]
Can you see whether  data.table::fread() works for this file?
It is faster and doesn't require an intermediate uncompressed copy of the data.

https://github.com/markziemann/Gene-function-imputation/blob/a6b63cbb2733fec5ba077c0b6b2d13e85fdda5e8/YeastSampleQualityFilter.Rmd#L23

More reading: https://www.r-bloggers.com/now-fread-from-data-table-can-read-gz-and-bz2-files-directly/

**Comment by megan-soria** [comment]
Updated code

commit ba143ae302a6eac2e97aa40c68c1b47005cccd77
