### ISSUE TITLE
location for html files

### ISSUE THREAD

**Issue by markziemann** [markziemann/Gene-function-imputation#4]
I think the html files should not be in the repo because they are "results". I have created a folder on the webserver in your hoome directory that you can copy the html to:

~/public/megan

Then the reports will be visible to anyone at the address:

http://118.138.234.73/public/megan/

**Comment by megan-soria** [comment]
I tried to connect to the web server using ssh:
ssh megan@118.138.234.73

but got this error message:
megan@118.138.234.73: Permission denied (publickey).

Can you please link me to a tutorial? I already installed the openssh server on my linux machine but I got lost as to how to connect to the web server to upload the file. Thanks!

**Comment by markziemann** [comment]
Temporary solution is to use the linux terminal in the Rstudio window. We can work out the permanent solution on Tuesday :)

**Comment by megan-soria** [comment]
HTMLs were transferred using 

file.copy("LearningResources.html", "~/public/megan")

in the R console
