### ISSUE TITLE
Suppress package startup messages

### ISSUE THREAD

**Issue by markziemann** [markziemann/Gene-function-imputation#6]
https://github.com/markziemann/Gene-function-imputation/blob/ba143ae302a6eac2e97aa40c68c1b47005cccd77/YeastSampleQualityFilter.Rmd#L11

Package loading mesages can take up a lot of space so its a good idea to silence them

```
suppressPackageStartupMessages({
library("getDEE2")
})
```

**Comment by megan-soria** [comment]
Rmd updated

commit 59f3f66b44b3717095b7a558bbfc6d7c46187fc3
