### ISSUE TITLE
Session information required

### ISSUE THREAD

**Issue by markziemann** [markziemann/Gene-function-imputation#9]
https://github.com/markziemann/Gene-function-imputation/blob/ba143ae302a6eac2e97aa40c68c1b47005cccd77/YeastSampleQualityFilter.Rmd#L132

at the end of the Rmd a session information chunk is good for reproducibility

```
```{r,session}
sessionInfo()
```
````

**Comment by megan-soria** [comment]
Rmd updated

commit 59f3f66b44b3717095b7a558bbfc6d7c46187fc3
